### ISSUE TITLE
Azure SWA returns 404 even after GitHub Actions are successful

### ISSUE THREAD

**Issue by Abbbdab** [geoffrich/svelte-adapter-azure-swa#120]
Trying to deploy a Sveltekit app as a SWA in a mono repo. The build process completed, and the logs in GitHub Actions show deployment and successful updates. However, visiting the page returns a 404. 

Here's the link to repo:
https://github.com/Abbbdab/the-motherbox

**Comment by geoffrich** [comment]
What happens if you set `api_location: "apps/dashboard/build/server"` in your SWA workflow file?

Per [the docs](https://github.com/geoffrich/svelte-adapter-azure-swa#azure-configuration):

> If your `app_location` is not the repository root `./` but `./my_app_location`, then you also need to change the `api_location` to `my_app_location/build/server` (but not the `output_location`).

See also https://github.com/geoffrich/svelte-adapter-azure-swa/pull/100

**Comment by Abbbdab** [comment]
@geoffrich legend mate! Deployment succeeded. I reckon we need to update the docs to cater for monorepos too. 

Great work!

**Comment by geoffrich** [comment]
Docs PRs welcome if you run into more monorepo-specific issues! I haven't done much with monorepos myself.
