### ISSUE TITLE
It looks like you don't need to prerender your index.svelte!

### ISSUE THREAD

**Issue by biltongza** [geoffrich/svelte-adapter-azure-swa#13]
I've managed to get a static web app working without a SvelteKit generated index.html by creating a dummy index.html in `/static` and then using the following config in my `staticwebapp.config.json`:

```
"routes": [
        {
            "route": "/index.html",
            "rewrite": "/api/__render"
        },
        {
            "route": "/",
            "rewrite": "/api/__render"
        }
    ],
    "navigationFallback": {
        "rewrite": "/api/__render"
    }
```

See https://github.com/Azure/static-web-apps/issues/671

This made my life easier because my index.svelte has dynamic content that doesn't work with prerendering, but now I can get the benefit of SSR instead of just using SPA mode :) figured I would share the info here.

**Comment by geoffrich** [comment]
Thanks for the confirmation! I'm hoping to get around to this soon. Currently tracking the work in #5, so I'll close this for now.

**Comment by geoffrich** [comment]
svelte-adapter-azure-swa@0.3.0 no longer requires `index.svelte` to be prerendered. Thanks again for helping to figure out a workaround!

**Comment by biltongza** [comment]
Hmm, I just tried it and something's not right. I removed my staticwebapp.config.json and my blank index.html, and it is generating a blank one for me as part of the build now and I can see the generated staticwebapp.config.json in the build output, but it doesn't look like it is getting respected because loading my site results in the blank index.html being served.

When I got it working first time, the staticwebapp.config.json lands up in `build/static`, where the one the adapter generates lands up in just `build`.

In my deployment workflow I've got `app_location: build/static` and `api_location: api`, do those seem correct?

**Comment by geoffrich** [comment]
You want the [following config](https://github.com/geoffrich/svelte-adapter-azure-swa#azure-configuration):

| property          | value          |
| ----------------- | -------------- |
| `app_location`    | `./`           |
| `api_location`    | `api`          |
| `output_location` | `build/static` |

The adapter-generated SWA config is supposed to end up in `build`, since we don't want it served with the rest of the static files.
