### ISSUE TITLE
Custom API functions may be caught by the sk_render function

### ISSUE THREAD

**Issue by geoffrich** [geoffrich/svelte-adapter-azure-swa#145]
Need to repro, but supposedly you need the following custom config if you define your own `/api` Azure functions:

```js
import azure from 'svelte-adapter-azure-swa';
/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		adapter: azure({
			apiDir: 'custom/api',
			customStaticWebAppConfig: {
				routes: [
					{
						"route": '/api/*',
						"methods": [
						  "GET",
						  "POST",
						],
					}
				],
			}
		})
	}
};
export default config;
```

It seems possible that the wildcard could redirect all API requests to the sk_render function instead of any custom ones?

https://github.com/geoffrich/svelte-adapter-azure-swa/blob/47ca37c13de36751d79ae431cc91c2f2d03026ba/index.js#L197-L201

Intended outcome: you can GET and POST to custom API Azure functions.

Overheard in [this post](https://qiita.com/shyamagu/items/9651a77c4791ae1033e4)

> *Important! If you do not enter this setting, the POST request will be absorbed by the render API for SSR and 404 will appear when calling POST! (PUT will be added if necessary) *

**Comment by kurt-mueller-osumc** [comment]
Hi Geoff,

First, thank you for this package. It has allowed my team and I to deploy our svelte kit frontend app into production. I appreciate the work you've done and it's made my professional life easier.

Second, I've been burned by this very issue :). The generated `staticwebapp.config.json` has this as the `routes` section:

```json
  "routes": [
    {
      "route": "*",
      "methods": [
        "POST",
        "PUT",
        "DELETE"
      ],
      "rewrite": "/api/__render"
    },
    {
      "route": "/_app/immutable/*",
      "headers": {
        "cache-control": "public, immutable, max-age=31536000"
      }
    }
  ]
```

This prevents `/api` requests from being proxied to the function app.

**Comment by jason-johnson** [comment]
I wonder if I'm hitting this issue.  I need to have some azure functions besides just the render so I set them up.  I tried version 4 but this causes the SWA to not see the render function anymore.  So I had to convert to V3 on my functions, then the local SWA CLI sees my functions but calling always fails with

```
 [2023-11-16T15:50:06.995Z] Executing 'Functions.sk_render' (Reason='This function was programmatically called via the host APIs.', Id=a725ba4b-76df-48ef-bde6-c5d54c5fde30)
[api] [2023-11-16T15:50:07.011Z] Error: Not found: /api/MyFunction
```

**Comment by jason-johnson** [comment]
Ah, yes now I understand the previous message. :)  The immutable section doesn't seem to do anything but the other section is blocking my API.  If I remove it then the API works again.  Why is the purpose of that section and what will break if it's just removed?

**Comment by ed-dpg** [comment]
I believe this is also affecting requests when using the [SWA database connection](https://learn.microsoft.com/en-us/azure/static-web-apps/database-overview) which creates a /data-api/* route.

**Comment by ed-dpg** [comment]
> I believe this is also affecting requests when using the [SWA database connection](https://learn.microsoft.com/en-us/azure/static-web-apps/database-overview) which creates a /data-api/* route.

Adding /data-api/* as well appears work, but I haven't done extensive testing:

`customStaticWebAppConfig: {
				routes: [
					{
						route: '/api/*',
						methods: ['GET', 'POST']
					},
					{
						route: '/data-api/*',
						methods: ['GET', 'POST']
					}
				]
			}`

**Comment by geoffrich** [comment]
v0.19.1 of the adapter should resolve this. I added additional dummy entries to the generated config so the request is not captured by the SvelteKit handler:

https://github.com/geoffrich/svelte-adapter-azure-swa/blob/018afa6fe4276390678892c6368bae48cf44e791/index.js#L199-L209

I was able to test that you can POST to a custom API endpoint now and it's part of the E2E tests. Please let me know if you encounter any further issues!
