### ISSUE TITLE
TypeError: Expected signal to be an instanceof AbortSignal

### ISSUE THREAD

**Issue by sagarp-patel** [geoffrich/svelte-adapter-azure-swa#155]
Hi Everyone, 

I am getting this error when using the azure static web app with SvelteKit. This error occurs when I am using airtable.js library or the @azure/storage-blob library. They both show the same error, and I am not sure what might be causing this error. One thing that is common between the two library is that they are imported via the const {Client} = require("library.js") method. It's seems the issue comes up when the fetch request is waiting for an Abort signal or so. I have tried everything and I am not sure how to solve this issue. I would appreciate any help with this. Thank you in advance! Also wanted to thank you for all the work you did with this library! It's pretty amazing!

**Comment by geoffrich** [comment]
I believe the [`esbuildOptions.keepNames`](https://github.com/geoffrich/svelte-adapter-azure-swa#esbuildoptions) option was added for this exact issue (see #148). Can you try setting that in your adapter config and see if it resolves the issue?

In your `svelte.config.js`:

```js
import azure from 'svelte-adapter-azure-swa';

export default {
	kit: {
		adapter: azure({
			esbuildOptions: {
				keepNames: true
			}
		})
	}
};
```

**Comment by sagarp-patel** [comment]
Hi! Thanks for the assistance! I was able to fix this by uninstalling and reinstalling the adapter as well, but the code you gave absolutely solved the issue for me! I appreciate the quick response! Thank you!
