### ISSUE TITLE
SWA produces a scheduler chunk. What is this?

### ISSUE THREAD

**Issue by polaroidkidd** [geoffrich/svelte-adapter-azure-swa#158]
Hi

I'm using this plugin for my SWA project and I've noticed in the output a scheduler.js chunk (check it out here https://meetup.dle.dev/)

I have no idea what this does or what purpose it serves. When I check the PageSpeedInsights report it claims that this script is  responsible for 1323 ms of JS execution time (See [results](https://pagespeed.web.dev/analysis/https-meetup-dle-dev/a2xzjxezfa?form_factor=mobile)).

Any idea what this is exactly? I couldn't find anything in the docs about it or in the SWA Docs.

Any help would be greatly appreciated here.

This is my svelte.config.js

```js
import { vitePreprocess } from '@sveltejs/kit/vite';
import azure from 'svelte-adapter-azure-swa';
import preprocess from 'svelte-preprocess';
/** @type {import('@sveltejs/kit').Config} */
const config = {
	preprocess: [
		vitePreprocess(),
		preprocess({
			postcss: true
		})
	],

	kit: {
		adapter: azure({
			esbuildOptions: {
				keepNames: true
			},
			customStaticWebAppConfig: {
				platform: {
					apiRuntime: 'node:18'
				}
			}
		}),
		alias: {
			'@mocks/*': './src/__mocks__/*',
			'@hooks/*': './src/hooks/*',
			'@model/*': './src/model/*',
			'@components/*': './src/lib/components/*',
			'@icons/*': './src/lib/components/icons/*',
			'@lib/*': './src/lib/*',
			'@pages/*': './src/pages/*',
			'@services/*': './src/lib/services/*',
			'@styles/*': './src/styles/*',
			'@utils/*': './src/lib/utils/*',
			'@assets/*': './src/assets/*'
		}
	}
};

export default config;

```

**Comment by geoffrich** [comment]
It looks like at least part of the chunk is part of [scheduler.js](https://github.com/sveltejs/svelte/blob/master/packages/svelte/src/runtime/internal/scheduler.js) from Svelte's runtime, that schedules DOM updates. It also appears to have some of Svelte's runtime code from [this file](https://github.com/sveltejs/svelte/blob/522d06a6add1de1779a87c83bee0a43163044c75/packages/svelte/src/runtime/internal/dom.js#L799), including code that runs [hydration](https://kit.svelte.dev/docs/glossary#hydration).

Optimizing your site's runtime performance is out of the scope of this adapter - I'd recommend posting in the help channel in the [Svelte discord](https://svelte.dev/chat) if you need further assistance.

**Comment by polaroidkidd** [comment]
It's weird that I don't get that when I build the project using the node adapter though. 

Either way, thanks for the clarification.
