### ISSUE TITLE
Sveltekit 2.0 support

### ISSUE THREAD

**Issue by sukeshpabolu** [geoffrich/svelte-adapter-azure-swa#168]
Please enable support for sveltekit 2.0.

 
![image](https://github.com/geoffrich/svelte-adapter-azure-swa/assets/107102468/1c29bf8c-9451-4efd-9ff8-d0df8f22c017)

**Comment by Assassyn** [comment]
This is a new issue as Svelte just updated its version. 

I have created a simple PR that updated all the dev dependencies

https://github.com/geoffrich/svelte-adapter-azure-swa/pull/169

**Comment by geoffrich** [comment]
Related: https://github.com/sveltejs/kit/pull/11316

**Comment by Jabronironi** [comment]
Is there an ETA on this issue?  It is blocking me from upgrading a few projects to SvelteKit 2.x.x.  Thank you!

**Comment by geoffrich** [comment]
v0.20 of the adapter now supports SvelteKit v2. This is a breaking change, so make sure to look at the release notes: https://github.com/geoffrich/svelte-adapter-azure-swa/releases/tag/v0.20.0
