### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by geoffrich** [geoffrich/svelte-adapter-azure-swa#19]
Some sort of tests would be good to make sure changes don't break anything. Possibly look at other adapters for inspiration, e.g. https://github.com/jthegedus/svelte-adapter-firebase/tree/main/tests

**Comment by biltongza** [comment]
Do you have any strong opinions on test runners/frameworks? I could certainly look into adding tests for the changes I did in #28.

**Comment by geoffrich** [comment]
Just merged a PR adding unit tests around the adapter build process + SWA config generation. We still need tests around the request/response adaption in the runtime and E2E tests.

**Comment by geoffrich** [comment]
Closing this since the important bits of the request/response adaption are under test. E2E tests are covered in #87.
