### ISSUE TITLE
Prerender true in README?

### ISSUE THREAD

**Issue by jochemvogel** [geoffrich/svelte-adapter-azure-swa#2]
It's necessary to have a `index.html` in your `build/public` (`output_location`) folder before you can deploy. In order to do that it's necessary to have a `export const prerender = true;` in your `index.svelte`.

I don't know if this is a normal thing for SvelteKit, because I'm still a little bit new in SvelteKit. But is it an idea to put this in the README in order to help others in the future?

It took me a while to figure that out. Couldn't figure out why my project didn't have a `index.html` in the build folder. Now I do. 🙂

I didn't have any other problems with configuring the adapter, btw. Took a while to figure some things out, but it was more project specific. Was looking for this adapter for a while, so thank you! 🙌🏼

**Comment by jochemvogel** [comment]
It makes sense that an `index.html` is necessary for a static website. There wouldn't be any starter point for the app if it wasn't there.

Maybe it's an [Oryx](https://github.com/microsoft/Oryx) thing, because that is what Azure Static Web Apps uses to build static applications. 

This was the log, btw:

```
---End of Oryx build logs---
Finished building app with Oryx
Failed to find a default file in the app artifacts folder (build/static). Valid default files: index.html,Index.html.
If your application contains purely static content, please verify that the variable 'app_location' in your workflow file points to the root of your application.
If your application requires build steps, please validate that a default file exists in the build output directory.
```

**Comment by geoffrich** [comment]
svelte-adapter-azure-swa@0.3.0 no longer requires `index.svelte` to be prerendered.
