### ISSUE TITLE
Application Insights integration

### ISSUE THREAD

**Issue by biltongza** [geoffrich/svelte-adapter-azure-swa#30]
I'm experimenting with improving App Insights logging. Currently all requests wind up in App Insights as a fairly nondescript function invocation:
<img width="514" alt="image" src="https://user-images.githubusercontent.com/2845704/152432040-2cd57ab0-6a8b-4a64-84f8-d45c84af2962.png">

There's no indication of what URL was rendered, and correlation if you are using App Insights client side in the browser does not work.

I got some correlation to work by simply adding this to `toRequest(context)`:

```
const traceparent = context.traceContext['traceparent'];
if(traceparent) {
	context.traceContext.traceparent = traceparent;
}
```

I also tried setting the actual original URL from `x-ms-original-url` in `context.traceContext.attributes` in the hopes that it would at least show up as a custom property/metric in App Insights, but that didn't seem to have any effect.

However, the [documentation](https://github.com/microsoft/applicationinsights-node.js#azure-functions) recommends wrapping HTTP triggers with some App Insights specific logic:

```
// Default export wrapped with Application Insights FaaS context propagation
export default async function contextPropagatingHttpTrigger(context, req) {
    // Start an AI Correlation Context using the provided Function context
    const correlationContext = appInsights.startOperation(context, req);

    // Wrap the Function runtime with correlationContext
    return appInsights.wrapWithCorrelationContext(async () => {
        const startTime = Date.now(); // Start trackRequest timer

        // Run the Function
        await httpTrigger(context, req);

        // Track Request on completion
        appInsights.defaultClient.trackRequest({
            name: context.req.method + " " + context.req.url,
            resultCode: context.res.status,
            success: true,
            url: req.url,
            duration: Date.now() - startTime,
            id: correlationContext.operation.parentId,
        });
        appInsights.defaultClient.flush();
    }, correlationContext)();
};
```

This does technically couple the adapter to App Insights strictly speaking, but you get App Insights for free with static web apps so I think it's an acceptable thing to do.

Thoughts?

**Comment by geoffrich** [comment]
I agree that we should make sure this is possible, but that seems like a lot of code to automatically include, which we would then have to allow users to configure. Is there a way that we can make this possible in user-land, e.g. in [hooks](https://kit.svelte.dev/docs/hooks)?

If we need to expose anything from the azure function request or context to make this possible, we can use the [`platform`](https://kit.svelte.dev/docs/adapters#supported-environments-platform-specific-context) object like the [Cloudflare](https://github.com/sveltejs/kit/tree/master/packages/adapter-cloudflare#environment-variables) adapter. Potentially, [update this line](https://github.com/geoffrich/svelte-adapter-azure-swa/blob/9d4bebb922daaf7839d491f66023f99ad21a8109/files/entry.js#L29) to pass context through:

```diff
- const rendered = await app.render(request); 
+ const rendered = await app.render(request, { platform: { context } }); 
```

**Comment by ncoder** [comment]
I'm a bit confused by this:
```ts
const traceparent = context.traceContext['traceparent'];
if(traceparent) {
	context.traceContext.traceparent = traceparent;
}
```

Doesn't this do nothing at all? (just re-assigning the original value back to itself)

FYI. i'm also trying to get application insights reporting in a sane place. No luck so far.

I'm going to try @geoffrich hint, pass the context in the platform, and then work on manually triggering the events using server hooks.

**Comment by tlaundal** [comment]
I agree this issue is quite broad, but there are aspects here I think are actionable.
A pain point for me is that all URLs show up as `/api/__render` in Application Insights. I would hope the adapter should document how, and make it easy to get the correct URLs.

**Comment by biltongza** [comment]
@ncoder that bit you're confused about propagates the traceparent to the next level :)

I haven't looked at this in a while, but I agree that the adapter passing down the context would be beneficial to be able to solve these kinds of things.

**Comment by ncoder** [comment]
No worries.
About telling app insights what the original URL is, that's covered in some comments i left in #126.
I even also added (just recently) a custom property for the user-agent. That's useful.

**Comment by ncoder** [comment]
context: "it's only available in production (and possibly when running with the SWA CLI"

Tip for the next person:
Yes, its' available with the SWA cli.

I've been using:
```sh
swa start --api-location build/server",
```

Watch your node version. I've had trouble with 18.xx 16.19.0 works for me.
