### ISSUE TITLE
/.auth routes

### ISSUE THREAD

**Issue by dreitzner** [geoffrich/svelte-adapter-azure-swa#31]
/.auth should be excluded from the render function I guess :)

https://kind-field-0d3164f03.1.azurestaticapps.net/user

https://kind-field-0d3164f03.1.azurestaticapps.net/.auth/aad

**Comment by geoffrich** [comment]
I think you have the wrong URL for login - it should be [/.auth/login/aad](https://kind-field-0d3164f03.1.azurestaticapps.net/.auth/login/aad). After going through the login flow at that URL, I get the following response from /user:

![image](https://user-images.githubusercontent.com/4992896/153907315-55cfd58d-6e38-423a-af92-bddf16978950.png)

Cool that this seems to work! I've been meaning to check it out but haven't had the time to dive deep yet. Keep me posted if you run into any other issues.

**Comment by dreitzner** [comment]
My bad....😂

Might use it more for work, as we did one project with it. Thank you for your work.
