### ISSUE TITLE
Handle prerendering breaking change

### ISSUE THREAD

**Issue by geoffrich** [geoffrich/svelte-adapter-azure-swa#36]
See https://github.com/sveltejs/kit/pull/4192. Prerendering is no longer done by the adapters.

**Comment by toastmastern** [comment]
Newbie q - is there any workaround i can specify in svelte.-config.js or so to temporary solve the issue?

**Comment by geoffrich** [comment]
Yeah, the workaround is to pin to the version of SvelteKit before the breaking change. I should hopefully get a new version of this adapter out this week.

**Comment by toastmastern** [comment]
Thanks!
