### ISSUE TITLE
Dynamically determine node version

### ISSUE THREAD

**Issue by geoffrich** [geoffrich/svelte-adapter-azure-swa#48]
https://github.com/geoffrich/svelte-adapter-azure-swa/pull/47 updated the adapter to target Node 16 instead of 12. This is good, but it would be better if we could allow the user to specify which node version to use. Otherwise, they'll be tied to the adapter Node version.

Here's how adapter-vercel does it:

https://github.com/sveltejs/kit/blob/3dae8e702641b5ee762b1892b7b7aa90e1c19a7c/packages/adapter-vercel/index.js#L388-L399

**Comment by geoffrich** [comment]
This could be solved using route-level config like the Vercel adapter: https://kit.svelte.dev/docs/adapter-vercel#deployment-configuration

**Comment by BernhardAuer** [comment]
Any news on this? I'd like to use node18 in SWA. Would it be possible to extend the customization level of the staticwebapp.config.json as proposed in #66 ?

**Comment by geoffrich** [comment]
Thanks for the bump @BernhardAuer - this was a quick feature add that is available in [0.17](https://github.com/geoffrich/svelte-adapter-azure-swa/releases/tag/v0.17.0).
