### ISSUE TITLE
Stop calling `writeStatic`

### ISSUE THREAD

**Issue by geoffrich** [geoffrich/svelte-adapter-azure-swa#52]
This is an upcoming breaking change for SvelteKit adapters.

See: ~https://github.com/sveltejs/kit/pull/5601~ https://github.com/sveltejs/kit/pull/5618

**Comment by aloker** [comment]
Is there any progress on this? We need to update SvelteKit to 1.0.0-next.383+ but can't because deployment to Azure SWA fails due to this. Is there anything we could do to help?

**Comment by geoffrich** [comment]
This is now resolved in version 0.8.0.
