### ISSUE TITLE
Need for additional esbuild options: exlude and keepNames

### ISSUE THREAD

**Issue by zjpalasz** [geoffrich/svelte-adapter-azure-swa#56]
Currently, when trying to bundle [node-postgres](https://node-postgres.com/), the following error occurs:
> node_modules/pg/lib/native/client.js:4:21: error: Could not resolve "pg-native" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)

The only solution I've come across is to `exclude: ['pg-native']`  via the esbuild options.

Additionally, when trying to bundle [azure/storage-blob](https://www.npmjs.com/package/@azure/storage-blob), the following error occurs:

> Error: TypeError: Expected signal to be an instanceof AbortSignal

It seems to be related to the sdk's dependency on node-fetch as noted [here](https://github.com/Azure/azure-sdk-for-js/issues/8483). The [suggestion](https://github.com/node-fetch/node-fetch/issues/784) of using `keepNames: true`, seems to resolve the issue.

**Comment by geoffrich** [comment]
Closed by #51. Please open another issue for `keepNames` if you find that it is still needed, per https://github.com/geoffrich/svelte-adapter-azure-swa/pull/51#issuecomment-1201491994
