### ISSUE TITLE
Multiple Set-Cookie not working in hook.js/ts in the Build. Only setting the first cookie.

### ISSUE THREAD

**Issue by saym97** [geoffrich/svelte-adapter-azure-swa#63]
**Sveltekit version: 1.0.0.next.405
Azure-SWA-adapter-version: ^0.10.0**

In hooks.js if we are sending multiple cookies in response header like this:
```
response.headers.append('Set-Cookie', cookie1);
response.headers.append('Set-Cookie', cookie2);
response.headers.append('Set-Cookie', cookie3);
```
The response header during dev environment looks like this:
```
Set-cookie : cookie1
Set-cookie : cookie2
Set-cookie : cookie3
```
and it sets all cookies. 

But when testing the build either with SWA CLI or deployed app. The response header looks like this:

`Set-Cookie: Cookie1; Cookie2; Cookie3`
This only takes Cookie1 into account and leave the rest.  

I have deployed my app on Vercel with Serverless Function  using Vercel adapter and on Azure with Nodejs adapter. On both , the `Set-Cookie` behave as expected and set all the cookies and response header also looks like this:
```
Set-cookie : cookie1
Set-cookie : cookie2
Set-cookie : cookie3
```

**Comment by FlippingBinary** [comment]
This code is overwriting duplicate headers, which would include `Set-cookie`.
https://github.com/geoffrich/svelte-adapter-azure-swa/blob/fbd26d404c8cd1c4ba82bd7b4c699b96aac687d2/files/entry.js#L70-L74

Cookies can also be set in their own separate key, according to https://github.com/Azure/azure-functions-host/issues/2737#issuecomment-568037718, but there appears to have been a problem with SWA and I don't know if it has been resolved: https://github.com/Azure/static-web-apps/issues/278. 

@geoffrich, should this adapter pull cookie headers out and create a cookies array from it? Or what's the best way to handle this?

**Comment by FlippingBinary** [comment]
I think I misread the problem. It looks like Netlify might have had a similar issue. That adapter solved it here: https://github.com/sveltejs/kit/blob/3cfbf2c72402f264bf13b992a8e8d77fa93cdcf3/packages/adapter-netlify/src/headers.js

In that case, `m` could be returned as a `cookies` array in the object that `toResponse` returns. Then, if it still doesn't work, it would be SWA's problem. I can write a pull-request for this.

**Comment by FlippingBinary** [comment]
I wrote a pull request for this issue that hopefully gets merged in, but the modern way of setting cookies is through the `cookies` parameter passed to actions, hooks, and endpoints. That's what I used to test the pull request. See https://kit.svelte.dev/docs/form-actions#anatomy-of-an-action
