### ISSUE TITLE
Sourcemaps aren't generated

### ISSUE THREAD

**Issue by FlippingBinary** [geoffrich/svelte-adapter-azure-swa#73]
Sourcemaps are extremely useful for debugging errors and exceptions, but the adapter currently does not output a sourcemap for the Azure function. We could set `sourcemap` to `external` in this object:

https://github.com/geoffrich/svelte-adapter-azure-swa/blob/fbd26d404c8cd1c4ba82bd7b4c699b96aac687d2/index.js#L80-L88

But perhaps it could be be rewritten to allow any build option:

    /** @type {BuildOptions} */
    const default_options = {
      ...esbuildOptions,
      entryPoints: [entry],
      outfile: join(apiDir, 'index.js'),
      bundle: true,
      platform: 'node',
      target: 'node16'
    };

**Comment by geoffrich** [comment]
Is there a reason not to generate sourcemaps, i.e. could we default to true? If not, I'd prefer a separate configuration option - passing all esbuild options couples us too tightly to esbuild (see also https://github.com/geoffrich/svelte-adapter-azure-swa/pull/51#issuecomment-1193493081).

**Comment by FlippingBinary** [comment]
If you want the adapter to be detached from esbuild, maybe the build options should be called `buildOptions` instead of `esbuildOptions` and the documentation could describe the available options in isolation from esbuild? The adapter could still accept options in an `esbuildOptions` key if `buildOptions` isn't present, but the documentation could describe that as deprecated in anticipation of switching to a different bundler. 

I would be happy with setting `sourcemap: 'linked'`, which is exactly what the adapters of the supported environments do.
