### ISSUE TITLE
bug: 'Could not resolve "./headers"'

### ISSUE THREAD

**Issue by FlippingBinary** [geoffrich/svelte-adapter-azure-swa#83]
# Bug

This bug can be reproduced by attempting to build the new SK app in `./demo`. It was introduced by 5a6a64f42349aad0da2d61b11e63189130eaf1dd because it adds a new `headers` module without making `adapt(...)` copy it to the build directory. 

# Proposed solution

Copy all the files in `./files` to the build directory:

```js
builder.copy(files, tmp, {
	replace: {
		SERVER: `${relativePath}/index.js`,
		MANIFEST: './manifest.js',
		DEBUG: debug.toString()
	}
});
```

It would replace these two code blocks:

https://github.com/geoffrich/svelte-adapter-azure-swa/blob/24365cbf315738dbad54093feac97aa119d31a9c/index.js#L63-L69

https://github.com/geoffrich/svelte-adapter-azure-swa/blob/24365cbf315738dbad54093feac97aa119d31a9c/index.js#L78

# Benefits

The provided constants `SERVER`, `MANIFEST`, and `DEBUG` could be used in more than just `entry.js`.

# Downside

This would take up more space in the build directory for files that aren't needed there.

**Comment by FlippingBinary** [comment]
As mentioned [here](https://github.com/geoffrich/svelte-adapter-azure-swa/pull/84#discussion_r997583748), the `api` directory does still need to be copied separately.

https://github.com/geoffrich/svelte-adapter-azure-swa/blob/24365cbf315738dbad54093feac97aa119d31a9c/index.js#L78

**Comment by geoffrich** [comment]
Merging #86 should prevent a bug like this from getting merged in the future, since we run the demo build as part of PR verification.
