### ISSUE TITLE
Error 500 in sverdle on demo app

### ISSUE THREAD

**Issue by victorhugoturnes** [geoffrich/svelte-adapter-azure-swa#85]
Internal server error on sverdle page

**Comment by FlippingBinary** [comment]
Some context would be helpful, but this is probably due to issue #83. Are you able to test PR #84 to see if the problem persists?

**Comment by FlippingBinary** [comment]
It's working fine in my environment, so I'm having trouble identifying what the problem could be. #83 has no impact when you `npm run dev` and prevents deploying it, so that couldn't be the problem.

Did you pull the latest version from this repository? How did you build/run it? What does the browser console and terminal console report?

**Comment by FlippingBinary** [comment]
Okay, thank you. That's good information. I think this is the relevant line:

```console
[swa] GET http://localhost:4280/api/__render - 404``
```

It looks like `npm run build` either failed or was not executed. If it failed, it's probably due to #83 and will be fixed soon.

**Comment by geoffrich** [comment]
I don't think it would be #83, since I haven't released those changes yet (see #76). Did you do `npm run build` before `swa start` as stated [in the README](https://github.com/geoffrich/svelte-adapter-azure-swa#running-locally-with-the-azure-swa-cli)?

> Run npm run build to build your project and swa start to start the emulator.

Right now you have to fully build the project to test with the SWA CLI. I'm not sure if there's a way around that.

**Comment by victorhugoturnes** [comment]
Adding the block

`
			builder.copy(files, tmp, {
				replace: {
					SERVER: `${relativePath}/index.js`,
					MANIFEST: './manifest.js',
					DEBUG: debug.toString()
				}
			});


` 
to the index file, instead of the fixes suggested on #83 changed the error, with it, it can be built and shows up the sverdle page, normally, but once you press the enter key it fails with `NetworkError when attempting to fetch resource.` and the following SWA log:

`
[swa] GET http://localhost:7071/api/__render (proxy)
[api] [2022-10-18T16:09:47.439Z] Executing 'Functions.render' (Reason='This function was programmatically called via the host APIs.', Id=2971b6f9-e4d9-4988-a8f3-29b735bc3d22)
[api] [2022-10-18T16:09:47.613Z] Executed 'Functions.render' (Succeeded, Id=2971b6f9-e4d9-4988-a8f3-29b735bc3d22, Duration=205ms)
[swa] GET http://localhost:4280/api/__render - 200
[swa] node "~/.nvm/versions/node/v16.16.0/lib/node_modules/@azure/static-web-apps-cli/dist/msha/server.js" exited with code 0
--> Sending SIGTERM to other processes..
[api] [2022-10-18T16:09:48.123Z] Language Worker Process exited. Pid=58208.
[api] [2022-10-18T16:09:48.123Z] node exited with code 143 (0x8F). .
[api] [2022-10-18T16:09:48.272Z] Worker process started and initialized.
[api] [2022-10-18T16:09:50.187Z] Host lock lease acquired by instance ID '0000000000000000000000008F717027'.
`

**Comment by victorhugoturnes** [comment]
I'm currently using archlinux, node v16.16.0, swa-cli 1.0.2.

I've created another sveltekit sverdle app, and added the adapter, no problems in compilations and the page loads without problems, but swa client crashes on submit
here is the error log:
```
[swa] GET http://localhost:5173/src/routes/sverdle/+page.svelte?svelte&type=style&lang.css (proxy)
[swa] GET http://localhost:4280/src/routes/sverdle/+page.svelte?svelte&type=style&lang.css - 304
[swa] node "~/.nvm/versions/node/v16.16.0/lib/node_modules/@azure/static-web-apps-cli/dist/msha/server.js" exited with code 0
--> Sending SIGTERM to other processes..
[api] [2022-10-18T20:59:39.780Z] Language Worker Process exited. Pid=14075.
[api] [2022-10-18T20:59:39.780Z] node exited with code 143 (0x8F). .
[run] cd "~/svelte-demo" && npm run dev exited with code SIGTERM
--> Sending SIGTERM to other processes..
[api] [2022-10-18T20:59:39.842Z] Language Worker Process exited. Pid=14220.
[api] [2022-10-18T20:59:39.842Z] node exited with code 143 (0x8F). .
[api] [2022-10-18T20:59:49.986Z] Worker process started and initialized.
^C[api] [2022-10-18T21:00:54.323Z] Language Worker Process exited. Pid=14234.
[api] [2022-10-18T21:00:54.323Z] node exited with code 130 (0x82). .
[api] [2022-10-18T21:00:54.324Z] Exceeded language worker restart retry count for runtime:node. Shutting down and proactively recycling the Functions Host to recover
[api] cd "~/svelte-demo/api" && func start --cors "*" --port 7071  exited with code 0
✖ SWA emulator stoped because API server exited with code 0.
```

I've put this on the cloud, in the following link: https://green-tree-00f72ff10.2.azurestaticapps.net, the project I used for this one is in my github, https://github.com/victorhugoturnes/svelte-swa.

Although on the cloud it doesnt crash, it returns 200 but doesnt update with the returned state of the sverdle, as in it resets the state of the page and ignores my submission.

**Comment by geoffrich** [comment]
I just deployed the local demo app in this repo (which uses the unreleased adapter version) to Azure SWA and it doesn't have the issue you described: https://polite-desert-00b80111e.2.azurestaticapps.net/sverdle

I suspect the error is related to #63 and cookies aren't being set correctly. This fix is in the main branch but not yet released. I'll cut a new release and see if that fixes it.

**Comment by geoffrich** [comment]
Can you try svelte-adapter-azure-swa v0.11 and see if that fixes the issue with your deployed demo?

**Comment by victorhugoturnes** [comment]
v0.11 worked.

Deployed is working fine, but not on swa-cli (same server exit error from before), although at this point I think its the swa tool itself that is being troublesome, I'll try it in a windows environment tomorrow see if helps.


Thanks for all the support and help

**Comment by victorhugoturnes** [comment]
Running the [StackBlitz](https://node.new/sveltekit) linked on the oficial svelteKit page is also erroring 500 on sverdle, 
![image](https://user-images.githubusercontent.com/29010563/196988735-53efde28-e002-4547-95e8-dccaf6995fa1.png)

So I'm assuming the error is internal to svelte or svelte kit and not relating to the adapter at  this point.

**Comment by geoffrich** [comment]
The stackblitz issue is CSRF related, see https://github.com/sveltejs/kit/issues/7277. Though maybe the SWA CLI is having the same issue?
