### ISSUE TITLE
Document API route limitation

### ISSUE THREAD

**Issue by geoffrich** [geoffrich/svelte-adapter-azure-swa#89]
See #78. If you have SvelteKit routes in `src/routes/api`, they will return a 404 when deployed to Azure. This is because Azure SWA reserves the `/api` path for individual Azure functions.

We could also issue some sort of warning if/when we detect these routes.

**Comment by geoffrich** [comment]
Thought on this: maybe this should be a build error instead. You shouldn't be defining SvelteKit /api routes for Azure SWA because they're just going to get ignored.

Could also provide a flag to ignore the error if needed, but I wouldn't want to add it prematurely.

**Comment by ObieMunoz** [comment]
@geoffrich Is there a solution/workaround for this currently?

**Comment by geoffrich** [comment]
We may need to warn/error about the new [/data-api route](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/announcing-database-connections-for-azure-static-web-apps-with/ba-p/3747831) as well.

**Comment by Tonton-Blax** [comment]
Thank you, I finally get why my api returned 404.
I guess I'm not the only one setting API related stuff in 'routes/api', maybe this should be stated straight in the main README?

**Comment by geoffrich** [comment]
I've opened #142 to throw a build error when this scenario is detected.
