### ISSUE TITLE
Note about local debugging doesn't appear to be necessary anymore

### ISSUE THREAD

**Issue by biltongza** [geoffrich/svelte-adapter-azure-swa#9]
It looks like [261](https://github.com/Azure/static-web-apps-cli/issues/261) and [286](https://github.com/Azure/static-web-apps-cli/issues/286) have been resolved and the CLI is working again, at least for now :)

**Comment by geoffrich** [comment]
Thanks for the report! Have you been able to successfully debug a SvelteKit app using the SWA CLI?

I'll test out the debugging setup a bit before closing this issue.

**Comment by biltongza** [comment]
It seems to be working for me, but honestly I've spent about 30 minutes with it so I'm not sure how confidently I can say it works other than it seems to serve my app just fine.

**Comment by geoffrich** [comment]
Just merged a PR that updates the docs accordingly. Thanks for the report!

I verified that it was mostly working, at least for the demo app. Noticed one issue where form submissions weren't working properly (and they are working on the deployed site), but I'll need to dig into that further. Likely another CLI issue, but it should work fine in most cases.
